# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoLabel(object):
    def setupUi(self, autoLabel):
        autoLabel.setObjectName("autoLabel")
        autoLabel.resize(1130, 890)
        self.verticalLayout = QtWidgets.QVBoxLayout(autoLabel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOpenDir = QtWidgets.QPushButton(autoLabel)
        self.pushButtonOpenDir.setObjectName("pushButtonOpenDir")
        self.horizontalLayout.addWidget(self.pushButtonOpenDir)
        self.pushButtonPrevImage = QtWidgets.QPushButton(autoLabel)
        self.pushButtonPrevImage.setObjectName("pushButtonPrevImage")
        self.horizontalLayout.addWidget(self.pushButtonPrevImage)
        self.pushButtonNextImage = QtWidgets.QPushButton(autoLabel)
        self.pushButtonNextImage.setObjectName("pushButtonNextImage")
        self.horizontalLayout.addWidget(self.pushButtonNextImage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fileListWidget = QtWidgets.QListWidget(autoLabel)
        self.fileListWidget.setMaximumSize(QtCore.QSize(256, 16777215))
        self.fileListWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.fileListWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.fileListWidget.setObjectName("fileListWidget")
        self.horizontalLayout_2.addWidget(self.fileListWidget)
        self.graphicsView = ZoomableGraphicsView(autoLabel)
        self.graphicsView.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.graphicsView.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout_2.addWidget(self.graphicsView)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.thumbnailPreview = QtWidgets.QListWidget(autoLabel)
        self.thumbnailPreview.setMaximumSize(QtCore.QSize(16777215, 101))
        self.thumbnailPreview.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.thumbnailPreview.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.thumbnailPreview.setIconSize(QtCore.QSize(100, 100))
        self.thumbnailPreview.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.thumbnailPreview.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.thumbnailPreview.setMovement(QtWidgets.QListView.Static)
        self.thumbnailPreview.setProperty("isWrapping", False)
        self.thumbnailPreview.setViewMode(QtWidgets.QListView.IconMode)
        self.thumbnailPreview.setObjectName("thumbnailPreview")
        self.verticalLayout.addWidget(self.thumbnailPreview)

        self.retranslateUi(autoLabel)
        QtCore.QMetaObject.connectSlotsByName(autoLabel)

    def retranslateUi(self, autoLabel):
        _translate = QtCore.QCoreApplication.translate
        autoLabel.setWindowTitle(_translate("autoLabel", "AutoLabelPlus"))
        self.pushButtonOpenDir.setText(_translate("autoLabel", "Open Dir"))
        self.pushButtonPrevImage.setText(_translate("autoLabel", "Prev Image"))
        self.pushButtonNextImage.setText(_translate("autoLabel", "Next Image"))
        self.fileListWidget.setSortingEnabled(True)
from zoomable_graphics_view import ZoomableGraphicsView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autoLabel = QtWidgets.QWidget()
    ui = Ui_autoLabel()
    ui.setupUi(autoLabel)
    autoLabel.show()
    sys.exit(app.exec_())
