# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoLabel(object):
    def setupUi(self, autoLabel):
        autoLabel.setObjectName("autoLabel")
        autoLabel.resize(689, 528)
        self.verticalLayout = QtWidgets.QVBoxLayout(autoLabel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonOpenDir = QtWidgets.QPushButton(autoLabel)
        self.pushButtonOpenDir.setObjectName("pushButtonOpenDir")
        self.horizontalLayout.addWidget(self.pushButtonOpenDir)
        self.pushButtonPrevImage = QtWidgets.QPushButton(autoLabel)
        self.pushButtonPrevImage.setObjectName("pushButtonPrevImage")
        self.horizontalLayout.addWidget(self.pushButtonPrevImage)
        self.pushButtonNextImage = QtWidgets.QPushButton(autoLabel)
        self.pushButtonNextImage.setObjectName("pushButtonNextImage")
        self.horizontalLayout.addWidget(self.pushButtonNextImage)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.graphicsView = ZoomableGraphicsView(autoLabel)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)

        self.retranslateUi(autoLabel)
        QtCore.QMetaObject.connectSlotsByName(autoLabel)

    def retranslateUi(self, autoLabel):
        _translate = QtCore.QCoreApplication.translate
        autoLabel.setWindowTitle(_translate("autoLabel", "AutoLabelPlus"))
        self.pushButtonOpenDir.setText(_translate("autoLabel", "Open Dir"))
        self.pushButtonPrevImage.setText(_translate("autoLabel", "Prev Image"))
        self.pushButtonNextImage.setText(_translate("autoLabel", "Next Image"))
from zoomable_graphics_view import ZoomableGraphicsView


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autoLabel = QtWidgets.QWidget()
    ui = Ui_autoLabel()
    ui.setupUi(autoLabel)
    autoLabel.show()
    sys.exit(app.exec_())
