# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_autoLabel(object):
    def setupUi(self, autoLabel):
        autoLabel.setObjectName("autoLabel")
        autoLabel.resize(762, 463)
        self.formLayout = QtWidgets.QFormLayout(autoLabel)
        self.formLayout.setObjectName("formLayout")
        self.graphicsView = QtWidgets.QGraphicsView(autoLabel)
        self.graphicsView.setObjectName("graphicsView")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.graphicsView)
        self.pushButtonOpenDir = QtWidgets.QPushButton(autoLabel)
        self.pushButtonOpenDir.setObjectName("pushButtonOpenDir")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButtonOpenDir)

        self.retranslateUi(autoLabel)
        QtCore.QMetaObject.connectSlotsByName(autoLabel)

    def retranslateUi(self, autoLabel):
        _translate = QtCore.QCoreApplication.translate
        autoLabel.setWindowTitle(_translate("autoLabel", "Form"))
        self.pushButtonOpenDir.setText(_translate("autoLabel", "Open Dir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    autoLabel = QtWidgets.QWidget()
    ui = Ui_autoLabel()
    ui.setupUi(autoLabel)
    autoLabel.show()
    sys.exit(app.exec_())
